### ISSUE TITLE
Rename 8vim_keyboard_layout_generator

### ISSUE THREAD

**Issue by Glitchy-Tozier** [sslater11/8vim_keyboard_layout_file_generator#1]
Request: Rename 8vim_keyboard_layout_generator to describe it more clearly and to avoid confusion with functionalities like this one: https://github.com/Glitchy-Tozier/8vim_keyboard_layout_calculator

I suggest 8vim_keyboard_layout_**file**_generator

(Also I love how we have the same naming-style)

**Comment by sslater11** [comment]
Haha can do!
I'm gonna give your script a look. I saw it the other day and was really impressed!

**Comment by sslater11** [comment]
Updated the file name and the project name :).

**Comment by Glitchy-Tozier** [comment]
> Haha can do!

Amazing, thank you!

> I'm gonna give your script a look. I saw it the other day and was really impressed!

Looking forward to getting some feedback!  :)
I'm doing my best to structurize the code, but I'm not sure how easy it is to understand the script right now.
